#ifndef ZBASEMAINWINDOW_GLOBAL_H
#define ZBASEMAINWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZBASEMAINWINDOW_LIBRARY)
#  define ZBASEMAINWINDOW_EXPORT Q_DECL_EXPORT
#else
#  define ZBASEMAINWINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // ZBASEMAINWINDOW_GLOBAL_H
